# Form implementation generated from reading ui file 'interviewpage.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 469)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ara = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ara.sizePolicy().hasHeightForWidth())
        self.ara.setSizePolicy(sizePolicy)
        self.ara.setMaximumSize(QtCore.QSize(275, 60))
        self.ara.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #d6d6d6); /* Üst açık alt koyu geçişli */\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 8px; /* Yuvarlak kenarlar */\n"
"    padding: 10px 20px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.3), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #f0f0f0, stop:1 #c8c8c8);\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4), inset -2px -2px 3px rgba(255, 255, 255, 0.8); /* Hover’da gölge artır */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d6d6d6, stop:1 #a0a0a0); /* Basılınca koyulaşan efekt */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5), inset -2px -2px 4px rgba(255, 255, 255, 0.3); /* İç gölge ile çökme efekti */\n"
"}\n"
"")
        self.ara.setObjectName("ara")
        self.gridLayout_2.addWidget(self.ara, 1, 0, 1, 1)
        self.tercihler = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tercihler.sizePolicy().hasHeightForWidth())
        self.tercihler.setSizePolicy(sizePolicy)
        self.tercihler.setMaximumSize(QtCore.QSize(275, 60))
        self.tercihler.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #d6d6d6); /* Üst açık alt koyu geçişli */\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 8px; /* Yuvarlak kenarlar */\n"
"    padding: 10px 20px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.3), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #f0f0f0, stop:1 #c8c8c8);\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4), inset -2px -2px 3px rgba(255, 255, 255, 0.8); /* Hover’da gölge artır */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d6d6d6, stop:1 #a0a0a0); /* Basılınca koyulaşan efekt */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5), inset -2px -2px 4px rgba(255, 255, 255, 0.3); /* İç gölge ile çökme efekti */\n"
"}\n"
"")
        self.tercihler.setObjectName("tercihler")
        self.gridLayout_2.addWidget(self.tercihler, 3, 0, 1, 1)
        self.projeGel = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projeGel.sizePolicy().hasHeightForWidth())
        self.projeGel.setSizePolicy(sizePolicy)
        self.projeGel.setMaximumSize(QtCore.QSize(275, 60))
        self.projeGel.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #d6d6d6); /* Üst açık alt koyu geçişli */\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 8px; /* Yuvarlak kenarlar */\n"
"    padding: 10px 20px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.3), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #f0f0f0, stop:1 #c8c8c8);\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4), inset -2px -2px 3px rgba(255, 255, 255, 0.8); /* Hover’da gölge artır */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d6d6d6, stop:1 #a0a0a0); /* Basılınca koyulaşan efekt */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5), inset -2px -2px 4px rgba(255, 255, 255, 0.3); /* İç gölge ile çökme efekti */\n"
"}\n"
"")
        self.projeGel.setObjectName("projeGel")
        self.gridLayout_2.addWidget(self.projeGel, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(275, 60))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 4px; /* Yuvarlak kenarlar */\n"
"    padding: 8px 12px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.1), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 1, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.baslik = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.baslik.setFont(font)
        self.baslik.setStyleSheet("")
        self.baslik.setObjectName("baslik")
        self.verticalLayout.addWidget(self.baslik)
        self.gridLayout_3.addWidget(self.frame_3, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.projeGond = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projeGond.sizePolicy().hasHeightForWidth())
        self.projeGond.setSizePolicy(sizePolicy)
        self.projeGond.setMaximumSize(QtCore.QSize(275, 60))
        self.projeGond.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #d6d6d6); /* Üst açık alt koyu geçişli */\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 8px; /* Yuvarlak kenarlar */\n"
"    padding: 10px 20px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.3), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #f0f0f0, stop:1 #c8c8c8);\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4), inset -2px -2px 3px rgba(255, 255, 255, 0.8); /* Hover’da gölge artır */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d6d6d6, stop:1 #a0a0a0); /* Basılınca koyulaşan efekt */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5), inset -2px -2px 4px rgba(255, 255, 255, 0.3); /* İç gölge ile çökme efekti */\n"
"}\n"
"")
        self.projeGond.setObjectName("projeGond")
        self.gridLayout.addWidget(self.projeGond, 0, 0, 1, 1)
        self.cikis = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cikis.sizePolicy().hasHeightForWidth())
        self.cikis.setSizePolicy(sizePolicy)
        self.cikis.setMaximumSize(QtCore.QSize(275, 60))
        self.cikis.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #d6d6d6); /* Üst açık alt koyu geçişli */\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 8px; /* Yuvarlak kenarlar */\n"
"    padding: 10px 20px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.3), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #f0f0f0, stop:1 #c8c8c8);\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4), inset -2px -2px 3px rgba(255, 255, 255, 0.8); /* Hover’da gölge artır */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d6d6d6, stop:1 #a0a0a0); /* Basılınca koyulaşan efekt */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5), inset -2px -2px 4px rgba(255, 255, 255, 0.3); /* İç gölge ile çökme efekti */\n"
"}\n"
"")
        self.cikis.setObjectName("cikis")
        self.gridLayout.addWidget(self.cikis, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tablo = QtWidgets.QTableWidget(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablo.sizePolicy().hasHeightForWidth())
        self.tablo.setSizePolicy(sizePolicy)
        self.tablo.setMaximumSize(QtCore.QSize(1100, 16777215))
        self.tablo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tablo.setRowCount(25)
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        self.tablo.horizontalHeader().setCascadingSectionResizes(True)
        self.tablo.horizontalHeader().setDefaultSectionSize(238)
        self.tablo.horizontalHeader().setHighlightSections(True)
        self.tablo.horizontalHeader().setMinimumSectionSize(52)
        self.tablo.horizontalHeader().setSortIndicatorShown(True)
        self.tablo.horizontalHeader().setStretchLastSection(True)
        self.tablo.verticalHeader().setDefaultSectionSize(53)
        self.tablo.verticalHeader().setMinimumSectionSize(42)
        self.tablo.verticalHeader().setSortIndicatorShown(True)
        self.tablo.verticalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.tablo, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 2, 0, 1, 3)
        self.frame_4.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ara.setText(_translate("MainWindow", "ARA"))
        self.tercihler.setText(_translate("MainWindow", "TERCİHLER"))
        self.projeGel.setText(_translate("MainWindow", "PROJESİ GELMİŞ OLANLAR"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "ARANACAK METNİ GİRİNİZ"))
        self.baslik.setText(_translate("MainWindow", "MÜLAKATLAR"))
        self.projeGond.setText(_translate("MainWindow", "PROJESİ GÖNDERİLMİŞ OLANLAR"))
        self.cikis.setText(_translate("MainWindow", "ÇIKIŞ"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Adınız Soyadınız"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Proje gonderilis tarihi"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Projenin gelis tarihi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
