# Form implementation generated from reading ui file 'MentorInterviewMenu.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MentorInterviewPage(object):
    def setupUi(self, MentorInterviewPage):
        MentorInterviewPage.setObjectName("MentorInterviewPage")
        MentorInterviewPage.setEnabled(True)
        MentorInterviewPage.resize(1016, 672)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MentorInterviewPage.sizePolicy().hasHeightForWidth())
        MentorInterviewPage.setSizePolicy(sizePolicy)
        MentorInterviewPage.setMinimumSize(QtCore.QSize(120, 40))
        MentorInterviewPage.setStyleSheet("\n"
"")
        MentorInterviewPage.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonFollowStyle)
        self.centralwidget = QtWidgets.QWidget(parent=MentorInterviewPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777214))
        self.centralwidget.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 2)
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setMaximumSize(QtCore.QSize(350, 100))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tumGorusme = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tumGorusme.sizePolicy().hasHeightForWidth())
        self.tumGorusme.setSizePolicy(sizePolicy)
        self.tumGorusme.setMinimumSize(QtCore.QSize(160, 40))
        self.tumGorusme.setMaximumSize(QtCore.QSize(160, 123123))
        self.tumGorusme.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #d6d6d6); /* Üst açık alt koyu geçişli */\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 8px; /* Yuvarlak kenarlar */\n"
"    padding: 10px 20px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.3), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #f0f0f0, stop:1 #c8c8c8);\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4), inset -2px -2px 3px rgba(255, 255, 255, 0.8); /* Hover’da gölge artır */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d6d6d6, stop:1 #a0a0a0); /* Basılınca koyulaşan efekt */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5), inset -2px -2px 4px rgba(255, 255, 255, 0.3); /* İç gölge ile çökme efekti */\n"
"}")
        self.tumGorusme.setObjectName("tumGorusme")
        self.gridLayout_2.addWidget(self.tumGorusme, 0, 0, 1, 1)
        self.ara = QtWidgets.QPushButton(parent=self.frame_4)
        self.ara.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ara.sizePolicy().hasHeightForWidth())
        self.ara.setSizePolicy(sizePolicy)
        self.ara.setMinimumSize(QtCore.QSize(160, 40))
        self.ara.setMaximumSize(QtCore.QSize(160, 40))
        self.ara.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #d6d6d6); /* Üst açık alt koyu geçişli */\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 8px; /* Yuvarlak kenarlar */\n"
"    padding: 10px 20px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.3), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #f0f0f0, stop:1 #c8c8c8);\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4), inset -2px -2px 3px rgba(255, 255, 255, 0.8); /* Hover’da gölge artır */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d6d6d6, stop:1 #a0a0a0); /* Basılınca koyulaşan efekt */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5), inset -2px -2px 4px rgba(255, 255, 255, 0.3); /* İç gölge ile çökme efekti */\n"
"}")
        self.ara.setObjectName("ara")
        self.gridLayout_2.addWidget(self.ara, 0, 1, 1, 1)
        self.tercihler = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tercihler.sizePolicy().hasHeightForWidth())
        self.tercihler.setSizePolicy(sizePolicy)
        self.tercihler.setMinimumSize(QtCore.QSize(160, 40))
        self.tercihler.setMaximumSize(QtCore.QSize(160, 40))
        self.tercihler.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #d6d6d6); /* Üst açık alt koyu geçişli */\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 8px; /* Yuvarlak kenarlar */\n"
"    padding: 10px 20px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.3), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #f0f0f0, stop:1 #c8c8c8);\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4), inset -2px -2px 3px rgba(255, 255, 255, 0.8); /* Hover’da gölge artır */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d6d6d6, stop:1 #a0a0a0); /* Basılınca koyulaşan efekt */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5), inset -2px -2px 4px rgba(255, 255, 255, 0.3); /* İç gölge ile çökme efekti */\n"
"}")
        self.tercihler.setObjectName("tercihler")
        self.gridLayout_2.addWidget(self.tercihler, 1, 0, 1, 1)
        self.cikis = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.cikis.sizePolicy().hasHeightForWidth())
        self.cikis.setSizePolicy(sizePolicy)
        self.cikis.setMinimumSize(QtCore.QSize(160, 40))
        self.cikis.setMaximumSize(QtCore.QSize(160, 40))
        self.cikis.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #d6d6d6); /* Üst açık alt koyu geçişli */\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 8px; /* Yuvarlak kenarlar */\n"
"    padding: 10px 20px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.3), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #f0f0f0, stop:1 #c8c8c8);\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4), inset -2px -2px 3px rgba(255, 255, 255, 0.8); /* Hover’da gölge artır */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d6d6d6, stop:1 #a0a0a0); /* Basılınca koyulaşan efekt */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5), inset -2px -2px 4px rgba(255, 255, 255, 0.3); /* İç gölge ile çökme efekti */\n"
"}")
        self.cikis.setObjectName("cikis")
        self.gridLayout_2.addWidget(self.cikis, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setMaximumSize(QtCore.QSize(470, 110))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(232, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(445, 42))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 4px; /* Yuvarlak kenarlar */\n"
"    padding: 8px 12px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.1), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(222, 40))
        self.comboBox.setMaximumSize(QtCore.QSize(445, 42))
        self.comboBox.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.comboBox.setToolTipDuration(-1)
        self.comboBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:1 #d6d6d6); /* Üst açık alt koyu geçişli */\n"
"    border: 3px solid #b0b0b0; /* Hafif koyu kenarlık */\n"
"    border-radius: 8px; /* Yuvarlak kenarlar */\n"
"    padding: 10px 20px; /* Dolgunluk sağlamak için iç boşluk */\n"
"    font-size: 12px;\n"
"    color: black;\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.3), inset -2px -2px 3px rgba(255, 255, 255, 0.6); /* Dış gölge ve iç parlama efekti */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #f0f0f0, stop:1 #c8c8c8);\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4), inset -2px -2px 3px rgba(255, 255, 255, 0.8); /* Hover’da gölge artır */\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d6d6d6, stop:1 #a0a0a0); /* Basılınca koyulaşan efekt */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5), inset -2px -2px 4px rgba(255, 255, 255, 0.3); /* İç gölge ile çökme efekti */\n"
"}\n"
"")
        self.comboBox.setMinimumContentsLength(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_5, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tablo = QtWidgets.QTableWidget(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tablo.sizePolicy().hasHeightForWidth())
        self.tablo.setSizePolicy(sizePolicy)
        self.tablo.setMinimumSize(QtCore.QSize(500, 0))
        self.tablo.setMaximumSize(QtCore.QSize(1300, 450))
        self.tablo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tablo.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: blue;\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"")
        self.tablo.setRowCount(30)
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.tablo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(7, item)
        self.tablo.horizontalHeader().setCascadingSectionResizes(True)
        self.tablo.horizontalHeader().setDefaultSectionSize(140)
        self.tablo.horizontalHeader().setSortIndicatorShown(True)
        self.tablo.horizontalHeader().setStretchLastSection(True)
        self.tablo.verticalHeader().setDefaultSectionSize(30)
        self.tablo.verticalHeader().setSortIndicatorShown(True)
        self.tablo.verticalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.tablo, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 2, 0, 1, 2)
        MentorInterviewPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MentorInterviewPage)

        self.menubar.setGeometry(QtCore.QRect(0, 0, 1016, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        MentorInterviewPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MentorInterviewPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MentorInterviewPage.setStatusBar(self.statusbar)

        self.retranslateUi(MentorInterviewPage)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MentorInterviewPage)

    def retranslateUi(self, MentorInterviewPage):
        _translate = QtCore.QCoreApplication.translate
        MentorInterviewPage.setWindowTitle(_translate("MentorInterviewPage", "Mentor menu"))
        self.label.setText(_translate("MentorInterviewPage", "MENTOR MENU"))
        self.tumGorusme.setText(_translate("MentorInterviewPage", "TÜM GÖRÜŞMELER"))
        self.ara.setText(_translate("MentorInterviewPage", "ARA"))
        self.tercihler.setText(_translate("MentorInterviewPage", "TERCİHLER"))
        self.cikis.setText(_translate("MentorInterviewPage", "ÇIKIŞ"))
        self.lineEdit.setPlaceholderText(_translate("MentorInterviewPage", "ARANACAK METNİ GİRİNİZ"))
        self.comboBox.setItemText(0, _translate("MentorInterviewPage", "VIT projesinin tamamına katılması uygun olur"))
        self.comboBox.setItemText(1, _translate("MentorInterviewPage", "VIT projesi ilk IT egitimi alanına yonlendirilmesi uygun olur"))
        self.comboBox.setItemText(2, _translate("MentorInterviewPage", "VIT projesi ingilizce egitimi alanına yonlendirilmesi uygun olur"))
        self.comboBox.setItemText(3, _translate("MentorInterviewPage", "VIT projesi KAPSAMINDA DİREKT YÖNLENDİRİLMESİ uygun olur"))
        self.comboBox.setItemText(4, _translate("MentorInterviewPage", "Direkt bireysel koçluk ile işe yonlendirilemesi uygun olur"))
        self.comboBox.setItemText(5, _translate("MentorInterviewPage", "Bir sonraki VIT projesine katılması uygun olur"))
        self.comboBox.setItemText(6, _translate("MentorInterviewPage", "BAŞKA BİR SEKTÖRE YÖNLENDİRİLMELİ"))
        self.comboBox.setItemText(7, _translate("MentorInterviewPage", "DİĞER"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("MentorInterviewPage", "Görüşme Tarihi"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("MentorInterviewPage", "VIT"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("MentorInterviewPage", "Ad Soyad"))
        item = self.tablo.horizontalHeaderItem(3)
        item.setText(_translate("MentorInterviewPage", "Mentor"))
        item = self.tablo.horizontalHeaderItem(4)
        item.setText(_translate("MentorInterviewPage", "Puan"))
        item = self.tablo.horizontalHeaderItem(5)
        item.setText(_translate("MentorInterviewPage", "Durum"))
        item = self.tablo.horizontalHeaderItem(6)
        item.setText(_translate("MentorInterviewPage", "IT Bilgisi"))
        item = self.tablo.horizontalHeaderItem(7)
        item.setText(_translate("MentorInterviewPage", "Yorumlar"))
from PyQt6.QtWidgets import QWidget



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MentorInterviewPage = QtWidgets.QMainWindow()
    ui = Ui_MentorInterviewPage()
    ui.setupUi(MentorInterviewPage)
    MentorInterviewPage.show()
    sys.exit(app.exec())
