# Form implementation generated from reading ui file 'PROJE.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 791, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(280, 30, 271, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 30, 221, 20))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setGeometry(QtCore.QRect(110, 160, 181, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(12, 10, 161, 28))
        self.pushButton.setObjectName("pushButton")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setGeometry(QtCore.QRect(530, 170, 181, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 171, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setGeometry(QtCore.QRect(300, 220, 181, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 10, 171, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame)
        self.frame_6.setGeometry(QtCore.QRect(90, 420, 181, 41))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 10, 171, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame)
        self.frame_7.setGeometry(QtCore.QRect(530, 410, 181, 41))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 10, 171, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame)
        self.frame_8.setGeometry(QtCore.QRect(300, 340, 181, 41))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 10, 171, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_3.clicked.connect(self.myFunction)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "  TERCIH ADMIN  MENU"))
        self.pushButton.setText(_translate("MainWindow", "BASVURULAR"))
        self.pushButton_2.setText(_translate("MainWindow", "MENTOR GORUSMESI"))
        self.pushButton_3.setText(_translate("MainWindow", "MULAKATLAR"))
        self.pushButton_4.setText(_translate("MainWindow", "KAPAT"))
        self.pushButton_5.setText(_translate("MainWindow", "ANA MENU"))
        self.pushButton_6.setText(_translate("MainWindow", "ADMIN MENU"))

    def myFunction(self):
    # Bu işlev, test düğmesine tıklandığında çağrılacak işlemi gerçekleştirir.
        print("Basvurular düğmesine tıklandı!")

    def mentor_gorusmesi(self):
        print("MENTOR GORUSMESI düğmesine tıklandı!")

    def mulakatlar(self):
        print("MULAKATLAR düğmesine tıklandı!")

    def kapat(self):
        print("KAPAT düğmesine tıklandı!")

    def ana_menu(self):
        print("ANA MENU düğmesine tıklandı!")

    def admin_menu(self):
        print("ADMIN MENU düğmesine tıklandı!")

    def show_giris_sayfasi(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
